import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { TFunction, withTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Navbar } from "@/components/layout/navbar";
import style from "@/styles/Home.module.css";

type Props = {
  t: TFunction;
};

const Home: NextPage<Props> = ({ t }) => {
  return (
    <>
      <Head>
        <title>{t<string>("common:title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div id="scene">
        <div className="parallax-3" />
        <div className="parallax-4" />
      </div>
      <main className={style.main}>
        <div className={style.description}>
          <h1 className={style.title}>Soy Suficiente</h1>
        </div>

        <div className={style.center}>
          <h2>Proximamente creceremos juntos!</h2>
        </div>

        <div className={style.grid}></div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  try {
    const i18nProps = await serverSideTranslations(ctx?.locale || "es-CO", [
      "common",
      "footer",
    ]);
    return {
      props: {
        ...i18nProps,
      },
    };
  } catch (error) {
    return { notFound: true };
  }
};

export default withTranslation()(Home);
