import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { TFunction, withTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Navbar } from "@/components/layout/navbar";
import Layout from "@/components/layout";
import { TPosts } from "@/types";
import PostsRepository from "@/repositories/posts.repository";
import HomeView from "@/components/home/HomeView";

type Props = {
  t: TFunction;
  posts: TPosts[];
};

const Home: NextPage<Props> = ({ t, ...props }) => {
  const layoutProps = {
    title: t("common:title"),
    description: t("common:description"),
    logo: "~/logoS.png",
  };
  return (
    <>
      <Head>
        <title>{t<string>("common:title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="scene">
        <div className="parallax-3" />
        <div className="parallax-4" />
      </div>
      <Layout {...layoutProps}>
        <HomeView {...props} />
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  try {
    const posts = await PostsRepository.getAll();
    const i18nProps = await serverSideTranslations(ctx?.locale || "es-CO", [
      "common",
      "footer",
    ]);

    return {
      props: {
        posts,
        ...i18nProps,
      },
    };
  } catch (error) {
    return { notFound: true };
  }
};

export default withTranslation()(Home);
